### ISSUE TITLE
The module-wide numeric constant declaration interprets as magic number.

### ISSUE THREAD

**Issue by cuurda** [wemake-services/wemake-python-styleguide#318]
# Bug report

This module-wide line produces Z432.
`MONGO_PORT = 27017  # defalut mongo port`

**Comment by sobolevn** [comment]
@cuurda what version of `wemake-python-styleguide` do you use?
Can you reproduce your error with the `master` version?

**Comment by sobolevn** [comment]
I am unable to reproduce this error with the `master` version. 
Here's the test for this specific case:

**Comment by cuurda** [comment]
I use the lastest pip version (0.4.0).

**Comment by cuurda** [comment]
I've just started to use this tool. It happened today. This is very good tool for yuong progers, that occasionally became techlead in some startup, and could not be reviewed. But I'd turned off Z306 from very begining. And now I think about "S104 Possible binding to all interfaces.", what to do with it in docker. But it is very good tool.

**Comment by sobolevn** [comment]
@cuurda you mean https://bandit.readthedocs.io/en/latest/plugins/b104_hardcoded_bind_all_interfaces.html?highlight=104 ?

**Comment by cuurda** [comment]
@sobolevn This error is not about port. This is about bind to 0.0.0.0, and not particular interface ip. As I know I can't know the ip address of docker container before it will be built and run. Maybe there is a tool or library that can get this interface ip in runtime. I will try to find it.

**Comment by sobolevn** [comment]
@cuurda sorry, I have misread the rule definition. 

Pass a parameter instead. And bind to a variable. Like I do here: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml#L38

**Comment by cuurda** [comment]
Is this error fixed in 0.5.0? I still catch it.

**Comment by sobolevn** [comment]
Seems to be fixed. Can you please provide your version information and a code sample that reproduces this issue?

**Comment by sobolevn** [comment]
Yes, it is still an issue. But, that's quite strange. Thanks for reporting it!

**Comment by sobolevn** [comment]
Are you willing to send a PR with the fix for this issue?

**Comment by cuurda** [comment]
Unfortunately, not now. Maybe on New Year vacations. I really apretiate this project, but now I can't be part of it.
